parameters:
    pexels_api_key: '%env(PEXELS_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\PexelsService:
        arguments:
            $apiKey: '%pexels_api_key%'

    App\Service\OpenAIService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'   
